# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questions_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='mark',
        ),
    ]
