# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170117_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.CharField(max_length=200),
        ),
    ]
