# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170118_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='votes',
            new_name='mark',
        ),
    ]
