# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170118_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='mark',
            field=models.FloatField(default=0),
        ),
    ]
