# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20170118_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choice',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
