# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_questions_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('choice', models.CharField(default=0, max_length=200)),
                ('mark', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
    ]
