# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='usernames',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
            preserve_default=False,
        ),
    ]
